import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Image from "next/image";
// import acceuil from "@/public/acceuil.jpg"
// import miels from "@/public/miels.jpg"
import logo from "@/public/logo.png";
import nuee from "@/public/nuee.png";
import Nav from "./Nav";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased h-screen overflow-x-hidden`}
      >
        <header className="h-[300px] pt-4 flex justify-center z-0">
          <div className="relative h-[300px] w-[600px]">
            <Image
              src={logo}
              alt="logo lenvolé"
              layout="fill"
              className="absolute object-contain"
            />
            <div>
              <Image
                src={nuee}
                alt="nuee lenvolé"
                layout="fill"
                className="absolute object-contain animate-fly"
              />
            </div>
          </div>
        </header>
        <Nav />

        <main className="p-2 sm:p-4 flex justify-center z-10">{children}</main>
        <footer>Indi Oyarzun - indi.oyarzun@gmail.com - Mercenac</footer>
      </body>
    </html>
  );
}
